In [1]:
# importing libraries
import pandas as pd
import glob
import os

In [2]:
# merging the files
joined_files = os.path.join("Resources/Hardik_Data", "*.csv")

In [3]:
# A list of all joined files is returned
joined_list = glob.glob(joined_files)

In [4]:
# Finally, the files are joined
df = pd.concat(map(pd.read_csv, joined_list), ignore_index=True)
print(df)

             Year  Consumer spending  Government spending  Government Share_%  \
0      2015-01-01               18.0                  5.0                22.0
1      2016-01-01               24.0                  7.0                21.0
2      2017-01-01               38.0                  9.0                19.0
3      2018-01-01               66.0                 13.0                17.0
4      2019-01-01               79.0                 11.0                12.0
...           ...                ...                  ...                 ...
70485         NaN                NaN                  NaN                 NaN
70486         NaN                NaN                  NaN                 NaN
70487         NaN                NaN                  NaN                 NaN
70488         NaN                NaN                  NaN                 NaN
70489         NaN                NaN                  NaN                 NaN

       Barrels per Day        ID Fuel Type Code         City State    ZIP  \
0                  NaN       NaN            NaN          NaN   NaN    NaN
1                  NaN       NaN            NaN          NaN   NaN    NaN
2                  NaN       NaN            NaN          NaN   NaN    NaN
3                  NaN       NaN            NaN          NaN   NaN    NaN
4                  NaN       NaN            NaN          NaN   NaN    NaN
...                ...       ...            ...          ...   ...    ...
70485              NaN  224376.0           ELEC    Milwaukee    WI  53212
70486              NaN  224377.0           ELEC       Austin    TX  78702
70487              NaN  224380.0           ELEC       Loomis    CA  95650
70488              NaN  224381.0           ELEC  Los Angeles    CA  91342
70489              NaN  224382.0           ELEC  Los Angeles    CA  91405

       ...          Street Address  Intersection Directions Access Days Time  \
0      ...                     NaN                      NaN              NaN
1      ...                     NaN                      NaN              NaN
2      ...                     NaN                      NaN              NaN
3      ...                     NaN                      NaN              NaN
4      ...                     NaN                      NaN              NaN
...    ...                     ...                      ...              ...
70485  ...  1555 N River Center Dr                      NaN   24 hours daily
70486  ...        720 Airport Blvd                      NaN   24 hours daily
70487  ...   6119 Horseshoe Bar Rd                      NaN   24 hours daily
70488  ...     13601 Glenoaks blvd                      NaN   24 hours daily
70489  ...      6723 Van Nuys Blvd                      NaN   24 hours daily

      Geocode Status Date Last Confirmed               Updated At   Open Date  \
0                NaN                 NaN                      NaN         NaN
1                NaN                 NaN                      NaN         NaN
2                NaN                 NaN                      NaN         NaN
3                NaN                 NaN                      NaN         NaN
4                NaN                 NaN                      NaN         NaN
...              ...                 ...                      ...         ...
70485            GPS          2022-07-25  2022-07-25 00:58:13 UTC  2022-07-24
70486            GPS          2022-07-25  2022-07-25 01:22:29 UTC  2022-07-24
70487            GPS          2022-07-25  2022-07-25 01:30:43 UTC  2022-07-25
70488            GPS          2022-07-25  2022-07-25 01:48:14 UTC  2022-07-25
70489            GPS          2022-07-25  2022-07-25 01:48:14 UTC  2022-07-25

      NG Vehicle Class Access Code Facility Type
0                  NaN         NaN           NaN
1                  NaN         NaN           NaN
2                  NaN         NaN           NaN
3                  NaN         NaN           NaN
4                  NaN         NaN           NaN
...                ...         ...           ...
70485              NaN      public           NaN
70486              NaN      public           NaN
70487              NaN      public           NaN
70488              NaN      public           NaN
70489              NaN      public           NaN

[70490 rows x 24 columns]

In [5]:
merged_df = pd.DataFrame(df)

In [6]:
merged_df.head()

,Year,Consumer spending,Government spending,Government Share_%,Barrels per Day,ID,Fuel Type Code,City,State,ZIP,...,Street Address,Intersection Directions,Access Days Time,Geocode Status,Date Last Confirmed,Updated At,Open Date,NG Vehicle Class,Access Code,Facility Type
0,2015-01-01,18.0,5.0,22.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-01-01,24.0,7.0,21.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017-01-01,38.0,9.0,19.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2018-01-01,66.0,13.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-01-01,79.0,11.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
#Exporting cleaned CSV files to the resources folder
merged_df.to_csv('Resources/Hardik_Data/Merged_Data.csv',index=False)